INSERT INTO consult_analyse_item
(id,
 version,
 member_id,
 appointment_id,
 patient_id,
 analyse_id,
 vetindicator,
 ownerindicator,
 comment,
 nomenclature,
 quantity,
 costing_id,
 added_by,
 added_on,
 last_edited_by,
 last_edited_on)
SELECT ANALYSELEMENT_ID,
       VERSION,
       MID,
       APPOINTMENT_ID,
       PATIENT_ID,
       ANALYSE_ID,
       VETINDICATOR,
       OWNERINDICATOR,
       COMMENT,
       NOMENCLATURE,
       QUANTITY,
       COSTING_ID,
       'system',
       now(),
       'system',
           now()
FROM vmas.analyselement
WHERE MID = 77;