INSERT INTO sales_refund_lineitem
(id,
 version,
 member_id,
 refund_id,
 nomenclature,
 quantity,
 taxed_type_enum,
 tax_good_percentage,
 tax_service_percentage,
 sales_price_ex_tax,
 processing_fee_ex_tax,
 total_inc_tax,
 tax_portion_of_product,
 tax_portion_of_processing_fee_service,
 category_id,
 costing_id,
 added_by,
 added_on,
 last_edited_by,
 last_edited_on)
SELECT LINEITEM_ID,
       VERSION,
       MID,
       REFUND_ID,
       NOMENCLATURE,
       QUANTITY,
       TAX,
       TAXGOODPERCENTAGE,
       TAXSERVICEPERCENTAGE,
       COST,
       PROCESSINGFEE,
       TOTAL,
       COSTTAXPORTION,
       PROCESSINGFEESERVICETAXPORTION,
       0,
       0,
       ADDEDBY,
       ADDEDON,
       LASTEDITEDBY,
       LASTEDITEDON
FROM vmas.lineitemrefund
WHERE mid = 77;