INSERT INTO consult_visit
(id,
 version,
 member_id,
 pet_id,
 appointment_id,
 weight,
 glucose,
 temperature,
 veterinarian,
 purpose,
 room,
 status,
 comments,
 estimated_time_in_minutes,
  invoice_number,
 invoice_status,
 invoice_date,
 reminder_send_date,
 reminder_send_date2,
 reminder_send_date3,
 sent_to_insurance,
 last_edited_by,
 last_edited_on,
 added_by,
 added_on)
SELECT VISIT_ID,
       VERSION,
       MID,
       PATIENT_ID,
       APPOINTMENT_ID,
       WEIGHT,
       GLUCOSE,
       TEMPERATURE,
       IfNull(VETERINARIAN, '') AS VETERINARIAN,
       IfNull(PURPOSE, '')      as PURPOSE,
       IfNull(ROOM, '')         AS ROOM,
       STATUS,
       COMMENTS,
       ESTIMATEDTIME,
       INVOICE_NR,
       INVOICE_STATUS,
       INVOICE_DATE,
       REMINDER_SEND_DATE,
       REMINDER2_SEND_DATE,
       REMINDER3_SEND_DATE,
       SENT_TO_INSURANCE,
       LASTEDITEDBY,
       LASTEDITEDON,
       ADDEDBY,
       ADDEDON
FROM vmas.visit
WHERE mid = 77;