    INSERT INTO consult_estimate_lineitem
    (id,
     version,
     member_id,
     estimate_id,
     pet_id,
     category_id,
     costing_id,
     nomenclature,
     quantity,
     taxed_type_enum,
     tax_good_percentage,
     tax_service_percentage,
     sales_price_ex_tax,
     processing_fee_ex_tax,
     total_inc_tax,
     tax_portion_of_product,
     tax_portion_of_processing_fee_service,
     has_print_label,
     added_by,
     added_on,
     last_edited_by,
     last_edited_on)
    SELECT ESTIMATELINEITEM_ID,
       VERSION,
       MID,
       ESTIMATE_ID,
       PATIENT_ID,
       LOOKUPCOSTINGCATEGORY_ID,
       0,
       NOMENCLATURE,
       QUANTITY,
       TAX,
       TAXGOODPERCENTAGE,
       TAXSERVICEPERCENTAGE,
       COST,
       PROCESSINGFEE,
       TOTAL,
       COSTTAXPORTION,
       PROCESSINGFEESERVICETAXPORTION,
       false,
       ADDEDBY,
       ADDEDON,
       LASTEDITEDBY,
       LASTEDITEDON
FROM vmas.estimatelineitem
where mid = 77