INSERT INTO consult_analyse_item
(id,
 version,
 member_id,
 appointment_id,
 pet_id,
 analyse_id,
 vet_indicator,
 owner_indicator,
 comment,
 nomenclature,
 quantity,
 costing_id,
    # TODO NEED TO JOIN WITH ANALYSE AND COPY THE INFORMATION FOR THE PRICING PART
 category_id,
    #  processing_fee_ex_tax,
#   sales_price_ex_tax,
#  tax_good_percentage,
#  tax_portion_of_processing_fee_service,
#  tax_portion_of_product,
#  tax_service_percentage,
 taxed_type_enum,
#  total_inc_tax,
 added_by,
 added_on,
 last_edited_by,
 last_edited_on)
SELECT ANALYSELEMENT_ID,
       VERSION,
       MID,
       APPOINTMENT_ID,
       PATIENT_ID,
       ANALYSE_ID,
       VETINDICATOR,
       OWNERINDICATOR,
       COMMENT,
       NOMENCLATURE,
       QUANTITY,
       COSTING_ID,
       0,
       0,
       'system',
       now(),
       'system',
       now()
FROM vmas.analyselement
WHERE MID = 77;