INSERT INTO new_vmas.sales_line_item
(id,
 version,
 member_id,
 category_id,
 costing_id,
 nomenclature,
 quantity,
 tax_good_percentage,
 tax_service_percentage,
 taxed_type_enum,
 sales_price_ex_tax,
 processing_fee_ex_tax,
 tax_portion_of_processing_fee_service,
 tax_portion_of_product,
 total_inc_tax,
 has_print_label,
 appointment_id,
 pet_id,
 added_by,
 added_on,
 last_edited_by,
 last_edited_on)
SELECT LINEITEM_ID,
       VERSION,
       MID,
       CATEGORY_ID,
       0,
       NOMENCLATURE,
       QUANTITY,
       TAXGOODPERCENTAGE,
       TAXSERVICEPERCENTAGE,
       TAX,
       COST,
       PROCESSINGFEE,
       PROCESSINGFEESERVICETAXPORTION,
       COSTTAXPORTION,
       TOTAL,
       false,
       APPOINTMENT_ID,
       PATIENT_ID,
       ADDEDBY,
       ADDEDON,
       LASTEDITEDBY,
       LASTEDITEDON
FROM vmas.lineitem
where mid = 77;