INSERT INTO customer_customer
(id,
 version,
 member_id,
 last_name,
 first_name,
 sur_name,
 middle_initial,
 email,
 address1,
 address2,
 address3,
 zip_code,
 city,
 state,
 home_phone,
 work_phone,
 emergency_contact,
 emergency_contact_phone,
 previous_veterinarian,
 previous_veterinarian_phone,
 comments, status,
 added_by,
 added_on,
 last_edited_by,
 last_edited_on,
 title,
 mobile_phone,
 newsletter,
 ubn,
 street,
 street_number)
SELECT CUSTOMER_ID,
       VERSION,
       MID,
       LASTNAME,
       FirstName,
       SURNAME,
       MIDDLEINITIAL,
       EMAIL,
       ADDRESS1,
       ADDRESS2,
       ADDRESS3,
       IfNull(REPLACE(TRIM(c.ZIPCODE), ' ', ''), '') AS zip_code,
       IfNull(c.CITY, '')  AS city,
       STATE,
       HOMEPHONE,
       WORKPHONE,
       EMERGENCYCONTACT,
       EMERGENCYCONTACTPHONE,
       VETERINARIAN,
       VETERINARIANPHONE,
       COMMENTS,
       STATUS,
       ADDEDBY,
       ADDEDON,
       LASTEDITEDBY,
       LASTEDITEDON,
       TITLE,
       MOBILEPHONE,
       NEWSLETTER,
       UBN,
       NULL,
       NULL

FROM vmas.customer c
where c.mid = 77;

update customer_customer
set zip_code = TRIM(REPLACE(zip_code, ' ', ''));