INSERT INTO admin_localmember
(id,
 version,
 member_id,
 local_member_name,
 address1,
 address2,
 address3,
 city,
 state,
 zip_code,
 phone1,
 phone2,
 added_by,
 added_on,
 last_edited_by,
 last_edited_on
 )
SELECT MEMBERLOCAL_ID,
       VERSION,
       MEMBER_ID,
       CLINIC,
       ADDRESS1,
       ADDRESS2,
       ADDRESS3,
       CITY,
       STATE,
       ZIPCODE,
       PHONE1,
       PHONE2,
       ADDED_BY,
       ADDED_ON,
       LAST_EDITED_BY,
       LAST_EDITED_ON
FROM vmas.thau_memberlocal where MEMBER_ID = 77;