 INSERT INTO customer_customer (
    added_on,
    id,
    last_edited_on,
    member_id,
    version,
    added_by,
    address1,
    address2,
    address3,
    city,
    comments,
    email,
    emergency_contact,
    emergency_contact_phone,
    first_name,
    home_phone,
    last_edited_by,
    last_name,
    middle_initial,
    mobile_phone,
    previous_veterinarian,
    previous_veterinarian_phone,
    state,
    sur_name,
    title,
    ubn,
    work_phone,
    zip_code,
    newsletter,
    status
)
SELECT
    c.ADDEDON AS added_on,
    c.CUSTOMER_ID AS id,
    c.LASTEDITEDON AS last_edited_on,
    c.MID AS member_id,
    c.VERSION AS version,
    c.ADDEDBY AS added_by,
    c.ADDRESS1 AS address1,
    c.ADDRESS2 AS address2,
    c.ADDRESS3 AS address3,
    IfNull(c.CITY, '-')  AS city,
    c.COMMENTS AS comments,
    c.EMAIL AS email,
    c.EMERGENCYCONTACT AS emergency_contact,
    c.EMERGENCYCONTACTPHONE AS emergency_contact_phone,
    c.FirstName AS first_name,
    c.HOMEPHONE AS home_phone,
    c.LASTEDITEDBY AS last_edited_by,
    c.LASTNAME AS last_name,
    c.MIDDLEINITIAL AS middle_initial,
    c.MOBILEPHONE AS mobile_phone,
    c.VETERINARIAN AS previous_veterinarian,
    c.VETERINARIANPHONE AS previous_veterinarian_phone,
    c.STATE AS state,
    c.SURNAME AS surname,
    c.TITLE AS title,
    c.UBN AS ubn,
    c.WORKPHONE AS work_phone,
    IfNull(c.ZIPCODE, '-') AS zip_code,
    c.NEWSLETTER AS newsletter,
    c.STATUS AS status
FROM vmas.customer c where c.mid = 77;