INSERT INTO customer.customer_pet (allergies,
                                   birthday,
                                   chip_date,
                                   deceased,
                                   deceased_date,
                                   gpwarning,
                                   insured,
                                   added_on,
                                   customer_id,
                                   id,
                                   last_edited_on,
                                   member_id,
                                   version,
                                   added_by,
                                   allergies_description,
                                   breed,
                                   breed_other,
                                   brief_description,
                                   chip_tattoo_id,
                                   comments,
                                   gpwarning_description,
                                   ideal_weight,
                                   insured_by,
                                   last_edited_by,
                                   name,
                                   rabies_id,
                                   species,
                                   sex)

SELECT patient.ALLERGIES            AS allergies,
       patient.BIRTHDAY             AS birthday,
       patient.CHIPDATE             AS chip_date,
       patient.DECEASED             AS deceased,
       patient.DECEASEDDATE         AS deceased_date,
       patient.GPWARNING            AS gpwarning,
       patient.INSURED              AS insured,
       patient.ADDEDON              AS added_on,
       patient.CUSTOMER_ID          AS customer_id,
       patient.PATIENT_ID           AS id,
       patient.LASTEDITEDON         AS last_edited_on,
       patient.MID                  AS member_id,
       patient.VERSION              AS version,
       patient.ADDEDBY              AS added_by,
       patient.ALLERGIESDESCRIPTION AS allergies_description,
       patient.BREED                AS breed,
       patient.BREEDOTHER           AS breed_other,
       patient.BRIEFDESCRIPTION     AS brief_description,
       patient.CHIPTATTOOID         AS chip_tattoo_id,
       patient.COMMENTS             AS comments,
       patient.DANGEROUSDESCRIPTION AS gpwarning_description,
       patient.IDEALWEIGHT          AS ideal_weight,
       patient.INSUREDBY            AS insured_by,
       patient.LASTEDITEDBY         AS last_edited_by,
       patient.PETNAME              AS name,
       patient.RABIESID             AS rabies_id,
       patient.SPECIES              AS species,
       patient.SEX                  AS sex
FROM vmas.patient patient
WHERE patient.mid = 77;