 INSERT INTO admin_member
(id,
 version,
 active,
 application_name,
 application_redirect,
 application_view,
 local_member_select_required,
 name,
 password,
 short_code,
 simultaneous_users,
 start_date,
 stop_date,
 added_by,
 added_on,
 last_edited_by,
 last_edited_on)
SELECT MEMBER_ID,
       VERSION,
       'Y',
       'app_name',
       'redirect',
       'view',
       'Y',
       NAME,
       PASSWORD,
       SHORT_CODE,
       SIMULTANEOUSUSERS,
       START,
       STOP,
       'system',
       now(),
       'system',
       now()
FROM vmas.thau_member
WHERE MEMBER_ID = 77;