server:
  port: 9004

spring:
  messages:
    basename: customer/messages




  datasource:
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:~/customer/database/customer;sql.syntax_mys=true
    username: SA
  jpa:
    database-platform: org.hibernate.dialect.HSQLDialect
    hibernate:
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    database: hsql
    properties:
      javax:
        persistence:
          schema-generation:
            scripts:
              action: create
              create-target: ./customer-module/hsql-create.sql



#  datasource:
#    url: jdbc:mysql://localhost:3306/customer
#    username: root
#    password: root
#  jpa:
#    database-platform: org.hibernate.dialect.MariaDBDialect
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    generate-ddl: true
#    database: mysql
#    properties:
#      javax:
#        persistence:
#          schema-generation:
#            scripts:
#              action: create
#              create-target: ./customer-module/maria-create.sql

#    properties:
#      hibernate:
#        show_sql: false
#        use_sql_comments: false
#        format_sql: false
#        use_jdbc_metadata_defaults: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.tool.schema: DEBUG