server:
  port: 9003

  http:
    multipart:
      enabled: false

  datasource:
    name: scoreinformation
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:~/scorekeeperInformation/database/scorekeeperInformation;sql.syntax_mys=true
    username: SA
  jpa:
    database: hsql
    hibernate:
      ddl-auto: update  # validate or update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        generate-ddl: no
        show_sql: false
        use_sql_comments: false
        format_sql: false
        use_jdbc_metadata_defaults: false

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG