server:
  port: 9002

spring:
  datasource:
    name: teammover
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:~/teammover/database/teammover;sql.syntax_mys=true
    username: SA
  jpa:
    database: hsql
    hibernate:
      ddl-auto: update  # validate or update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        generate-ddl: no
        show_sql: true
        use_sql_comments: false
        format_sql: false
        use_jdbc_metadata_defaults: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO