app:

server:
  port: 9001

spring:
  messages:
    basename: admin/messages

  datasource:
    url: jdbc:mysql://localhost:3306/admin
    username: root
    password: root
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update  # validate or update
    show-sql: true
    generate-ddl: true
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        generate-ddl: no
        show_sql: true
        use_sql_comments: false
        format_sql: false
        use_jdbc_metadata_defaults: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.tool.schema: INFO