app:

server:
  port: 9001

spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  datasource:
    name: admin-module
    driverClassName: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:~/admin-module/database/admin-module;sql.syntax_mys=true
    username: SA
  jpa:
    database: hsql
    hibernate:
      ddl-auto: update  # validate or update

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        generate-ddl: no
        show_sql: true
        use_sql_comments: false
        format_sql: false
        use_jdbc_metadata_defaults: false

  thymeleaf:
    cache: true
logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO