INSERT INTO new_vmas.supply_supply
(id,
 version,
 member_id,
 barcode,
 buy_quantity_per_order,
 item_number,
 min_quantity_for_alert,
 nomenclature,
 price,
 quantity_per_package,
 distributor_id,
 description_of_distributor,
 distributor_name,
 added_by,
 added_on,
 last_edited_by,
 last_edited_on)
SELECT SUPPLIES2_ID,
       VERSION,
       MID,
       BARCODE,
       BUYQUANTITY,
       ITEMNUMBER,
       MINQUANTITY,
       NOMENCLATURE,
       PRICE,
       QUANTITYPERPACKAGE,
       null,
       DISTDESCRIPTION,
       DISTRIBUTOR,
       USERNAME,
       now(),
       'system',
       LASTALTERED
FROM vmas.supplies2
WHERE MID = 77;