INSERT INTO supply_product_price_promotion
(id,
 version,
 product_id,
 start_date, end_date,
 sales_price_ex_tax,
 processing_fee,
 reduction_percentage,
 buy_XforY_X,
 buy_XforY_Y,
 pricing_type,
 member_id,
 added_by,
 added_on,
 last_edited_by,
 last_edited_on)
SELECT COSTINGSPECIALPRICE_ID,
       VERSION,
       Costing_ID,
       STARTDATE,
       ENDDATE,
       COST,
       PROCESSINGFEE,
       REDUCTION,
       0,
       0,
       'S',
       MID,
       ADDEDBY,
       ADDEDON,
       LASTEDITEDBY,
       LASTEDITEDON
FROM vmas.costingspecialprice
where mid = 77