INSERT INTO supply_costing
(id,
 version,
 member_id,
 lookupcostingcategory_id,
 nomenclature,
 sell_ex_tax_price,
 purchase_price,
 distributor,
 distributor_description,
 item_number,
 quantity_per_package,
 uplift,
 has_batch_nr,
 has_spillage,
 processing_fee,
 taxed,
 auto_reminder,
 reminder_nomenclature,
 interval_in_weeks,
 r_remove_pending_reminders_containing,
 short_code,
 deceased_pet_prompt,
 certificate_manufacturer,
 certificate_type,
 certificate_serial_number,
 certificate_vaccine_expires,
 instructions, prescription_label,
 supplies2_id,
 supplies2_id_indy_qty_deduction,
 added_by,
 added_on,
 last_edited_by,
 last_edited_on, barcode,
 deleted)
SELECT COSTING_ID,
       VERSION,
       MID,
       LOOKUPCOSTINGCATEGORY_ID,
       NOMENCLATURE,
       COST,
       PRICE,
       DISTRIBUTOR,
       DISTDESCRIPTION,
       ITEMNUMBER,
       QUANTITYPERPACKAGE,
       UPLIFT,
       BATCH_NR,
       SPILLAGE,
       PROCESSINGFEE,
       TAXED,
       AUTOREMINDER,
       RNOMENCLATURE,
       `INTERVAL`,
       RREMOVEPENDINGREMINDERSCONTAINING,
       CODE,
       IF(DECEASEDPETPROMPT = 1, 'y', 'n'),
       CERTIFICATEMANUFACTURER,
       CERTIFICATETYPE,
       CERTIFICATESERIALNUMBER,
       CERTIFICATEVACCINEEXPIRES,
       INSTRUCTIONS,
       PRESCRIPTIONLABEL,
       SUPPLIES2_ID,
       SUPPLIES2_IDINDYQTYDEDUCTION,
       ADDEDBY,
       ADDEDON,
       LASTEDITEDBY,
       LASTEDITEDON,
       BARCODE,
       DELETED
FROM vmas.costing
WHERE MID = 77;