INSERT INTO admin_user
(id,
 version,
 member_id,
 account,
 password,
 personnel_status,
 login_enabled,
 name,
 email,
  last_visit_date,
 number_of_visits,
 language,
 added_by,
 added_on,
 last_edited_by,
 last_edited_on,
 change_password)
SELECT USER_ID,
       VERSION,
       MEMBER_ID,
       ACCOUNT,
       PASSWORD,
       PERSONNEL_TYPE,
       LOGIN_ENABLED,
       NAME,
       EMAIL,
       LAST_VISIT_DATE,
       NUMBER_VISIT_DAYS,
       LANGUAGE,
       ADDED_BY,
       ADDED_ON,
       LAST_EDITED_BY,
       LAST_EDITED_ON,
       'N'
FROM vmas.thau_user
where member_id = 77;