INSERT INTO admin_member
(id,
 version,
 name,
 password,
 simultaneous_users,
 short_code,
 active,
 start_date,
 stop_date,
 application_name,
 application_redirect,
 application_view,
 local_member_select_required,
 added_by,
 added_on,
 last_edited_by,
 last_edited_on)
SELECT MEMBER_ID,
       VERSION,
       NAME,
       PASSWORD,
       SIMULTANEOUSUSERS,
       SHORT_CODE,
       ACTIVE,
       START,
       STOP,
       'VMAS',
       '',
       '',
       true,
       'migration',
       now(),
       'migration',
       now()
FROM vmas.thau_member