app:
  datasource:
    global:
      jdbc-url: jdbc:mysql://localhost:3306/new_vmas
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
    tenant:
      jdbc-url: jdbc:mysql://localhost:3306/new_vmas
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

spring:
  thymeleaf:
    cache: false  # TODO turn on for production

  messages:
    basename: admin.messages, shared.messages, customer.messages, lookup.messages,  supplyinventory.messages, sales.messages, consult.messages, vmas.messages, report.messages
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      naming:
        implicit-strategy: dwe.holding.admin.hibernatenamingstrategy.CustomImplicitNamingStrategy
      ddl-auto: update

    generate-ddl: false
    database: mysql
    properties:
      hibernate:
        jdbc.batch_size: 1000
        hibernate.order_updates: true
#      javax.persistence.schema-generation.create-source: metadata
#      javax.persistence.schema-generation.scripts.action: create
#      javax.persistence.schema-generation.scripts.create-target: create_new-vmas.sql
#      use_sql_comments: true

#        format_sql: true
#    show_sql: true
  ssl:
    bundle:
      jks:
        web-server:
          key:
            alias: "springboot-ssl"
          keystore:
            location: "classpath:springboot-ssl.p12"
            password: "vmasvmas"
            type: "PKCS12"
  devtools:
    restart:
      additional-exclude:
        - "admin-module-*.jar"
        - "**/admin-module-*.jar"
        - "lib/admin-module-*.jar"

  # Email Configuration
  mail:
    host: smtp.gmail.com
    port: 587
    username: dweholding@gmail.com
    password: xxhkpinfuogapgrz
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000


logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.hibernate.tool.schema: INFO
#    org.hibernate.SQL: DEBUG
#    org.hibernate.orm.jdbc.bind: TRACE
#    org.hibernate.type.descriptor.sql: TRACE


server:
  servlet:
    session:
      timeout: 15m
#    context-path: /gwz-vmas

  http2:
    enabled: true
  port: 8443
  address: 0.0.0.0
  ssl:
    bundle: web-server
    client-auth: none
